import type { Metadata } from "next";
import Pretendard from "@/styles/local-font";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn(Pretendard.className, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
